Areas/Admin/Controllers/LocationController.cs
using Event_management.BL;
using Event_managment.BL;
using Event_managment.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Event_managment.Areas.Admin.Controllers
{
    [Area("admin")]
    public class LocationController : Controller
    {
        private readonly ILocationService _locationService;
        private readonly IEventService _eventService;

        // Constructor
        public LocationController(ILocationService locationService, IEventService eventService)
        {
            _locationService = locationService;
            _eventService = eventService;
        }

        // GET: Admin/Location/List
        public IActionResult List()
        {
            List<TbLocation> lstLocations = _locationService.GetAll(); // Fetch all locations
            return View(lstLocations);
        }

        // GET: Admin/Location/Edit/{id}
        public IActionResult Edit(int? id)
        {
            TbLocation location = id != null ? _locationService.GetByID(id.Value) : new TbLocation();
            return View(location); // Return the view for editing
        }

        // POST: Admin/Location/Save
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(TbLocation location)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", location); // Return view with validation errors
            }

            // Check for uniqueness of the location name and address
            if (_locationService.IsLocationUnique(location.LocationName, location.Address, location.LocationId))
            {
                ModelState.AddModelError(string.Empty, "A location with the same name and address already exists.");
                return View("Edit", location); // Return view with error message
            }

            // Validate capacity
            if (!_locationService.IsCapacityValid(location.Capacity, location.LocationId))
            {
                ModelState.AddModelError(string.Empty, "The capacity can't be 0 or less than the current Participants.");
                return View("Edit", location); // Return view with error message
            }

            _locationService.Save(location); // Save the location
            return RedirectToAction("List"); // Redirect to the list of locations
        }

        // GET: Admin/Location/Delete/{id}
        public IActionResult Delete(int id)
        {
            _locationService.Delete(id); // Delete the location
            var eventIds = _locationService.GetRelatedEventsIDs(id);
            foreach (var eventId in eventIds)
            {
                _eventService.Delete(eventId);
            }
            return RedirectToAction("List"); // Redirect to the list
        }
    }
}

Areas/Admin/Views/Location/Edit.cshtml
@model TbLocation

<div class="content-wrapper">

    <div class="row">
        <div class="col-md-8 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Edit Location</h4>
                    <form class="forms-sample" method="post" enctype="multipart/form-data"
                          asp-controller="Location" asp-action="Save" role="form">
                        <input asp-for="LocationId" type="hidden" />
                        <div class="form-group">
                            <label for="exampleInputUsername1">@ResAdmin.lblLocation</label>
                            <input asp-for="LocationName" type="text" class="form-control" placeholder="@ResAdmin.lblLocation">
                            <span asp-validation-for="LocationName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputUsername1">@ResAdmin.lblAddress</label>
                            <input asp-for="Address" type="text" class="form-control" placeholder="@ResAdmin.lblAddress">
                            <span asp-validation-for="Address" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputUsername1">@ResAdmin.lblCity</label>
                            <input asp-for="City" type="text" class="form-control" placeholder="@ResAdmin.lblCity">
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputUsername1">@ResAdmin.lblState</label>
                            <input asp-for="State" type="text" class="form-control" placeholder="@ResAdmin.lblState">
                            <span asp-validation-for="State" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputUsername1">@ResAdmin.lblZipCode</label>
                            <input asp-for="ZipCode" type="number" class="form-control" placeholder="@ResAdmin.lblZipCode">
                            <span asp-validation-for="ZipCode" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputUsername1">@ResAdmin.lblCapacity</label>
                            <input asp-for="Capacity" type="number" class="form-control" placeholder="@ResAdmin.lblCapacity">
                            <span asp-validation-for="Capacity" class="text-danger"></span>
                        </div>
                        
                        <button type="submit" formmethod="post" class="btn btn-gradient-primary me-2">@ResGeneral.lblSave</button>
                        <a href="@Url.Action("List", "Location")" class="btn btn-light">@ResGeneral.lblCancel</a>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>
@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>

    @if (!ViewData.ModelState.IsValid)
    {
        <script>
            var errors = @Html.Raw(Json.Serialize(ViewData.ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage)));
            errors.forEach(function (error) {
                toastr.error(error);
            });
        </script>
    }
}

Areas/Admin/Views/Location/List.cshtml
@model List<TbLocation>

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Locations List</h4>
            <div class="card-description">
                <a href="/Admin/Location/Edit" class="btn btn-gradient-primary btn-fw">New</a>
            </div>
            <div class="table-responsive">
                <table id="order-listing" class="table table-striped">
                    <thead>
                        <tr>
                            <th> @ResAdmin.lblLocation </th>
                            <th> @ResAdmin.lblAddress </th>
                            <th> @ResAdmin.lblCity </th>
                            <th> @ResAdmin.lblState </th>
                            <th> @ResAdmin.lblZipCode </th>
                            <th> @ResAdmin.lblCapacity </th>
                            <th> @ResGeneral.lblAction </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var Location in Model)
                        {
                            <tr>
                                <td>@Location.LocationName </td>
                                <td> @Location.Address </td>
                                <td> @Location.City </td>
                                <td> @Location.State </td>                             
                                <td> @Location.ZipCode </td>
                                <td> @Location.Capacity </td>

                                <td>
                                    <a class="btn btn-gradient-info btn-fw" asp-controller="Location" asp-action="Edit" asp-route-id="@Location.LocationId">Edit </a>
                                    <a class="btn btn-gradient-danger btn-fw" asp-controller="Location" asp-action="Delete" asp-route-id="@Location.LocationId"
                                       onclick="return confirm('Are you sure you want to delete this category?');">
                                        Delete
                                    </a>
                                </td>
                            </tr>
                        }


                    </tbody>
                </table>
            </div>
           
        </div>
    </div>
</div>


@section Scripts
{
    <!-- Plugin js for this page -->
    <script src="~/Admin/vendors/datatables.net/jquery.dataTables.js"></script>
    <script src="~/Admin/vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script>
    <!-- End plugin js for this page -->
    <!-- Custom js for this page -->
    <script src="~/Admin/js/data-table.js"></script>

    <!-- End custom js for this page -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


}